[package]
name = "connective-unconscious"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"

[dependencies]
axum = "0.8"
axum-extra = "0.12"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.48", features = ["full"] }
tracing-subscriber = "0.3"
log = "0.4"
hypertext = "0.12"
tower-http = { version = "0.6", features = ["fs"] }
